### ISSUE TITLE
Failed at the dinossauro@0.0.5 postinstall script './postinstall.sh'

### ISSUE THREAD

**Issue by lgvo** [vieiralucas/dinossauro#1]
Looks like the URL (http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz) changed to (https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz)

**Comment by vieiralucas** [comment]
Can you provide more detail? 😸

**Comment by vieiralucas** [comment]
Fixed on #2
